name: CI devops By Maf
on:
  workflow_dispatch:            # manual "Run workflow" button
  push:
    branches: [ main, develop ] # runs on pushes to main/develop
  pull_request:
    branches: [ main, develop ]

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build and test with Maven
        run: mvn -B -ntp -f simple-api-student-main/pom.xml clean verify
