name: CI devops 2025

on:
  workflow_dispatch:                 # manual trigger
  push:
    branches: ["**"]                 # build on any branch
  pull_request:
    branches: ["**"]

jobs:
${{ github.ref_name == 'main' }}
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Build & test WITHOUT changing your code structure
      - name: Build and test with Maven (subfolder)
        if: ${{ hashFiles('simple-api-student-main/pom.xml') != '' }}
        run: mvn -B -ntp -f simple-api-student-main/pom.xml clean verify

      - name: Build and test with Maven (repo root)
        if: ${{ hashFiles('simple-api-student-main/pom.xml') == '' && hashFiles('pom.xml') != '' }}
        run: mvn -B -ntp clean verify

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      #  Login to Docker Hub (set DOCKERHUB_USERNAME & DOCKERHUB_TOKEN in repo Secrets)
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # --- Backend image ---
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api-student-main
          file: ./simple-api-student-main/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:${{ github.sha }}
          # build on all branches, push only on main
          push: ${{ github.ref == 'refs/heads/main' }}

      # --- Database image (optional: requires ./database/Dockerfile) ---
      - name: Build image and push database
        if: ${{ hashFiles('database/Dockerfile') != '' }}
        uses: docker/build-push-action@v6
        with:
          context: ./database
          file: ./database/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/main' }}

      # --- Httpd image (optional: requires ./web/Dockerfile) ---
      - name: Build image and push httpd
        if: ${{ hashFiles('web/Dockerfile') != '' }}
        uses: docker/build-push-action@v6
        with:
          context: ./web
          file: ./web/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/main' }}
