name: CI devops By Maf
on:
  # launch on main and develop
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      # checkout your github code
      - uses: actions/checkout@v4

      # set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # build & test (points to the subfolder without changing your code)
      - name: Build and test with Maven
        run: mvn -B -ntp -f simple-api-student-main/pom.xml clean verify
