# define job to build and publish docker images
build-and-push-docker-image:
  needs: test-backend
  runs-on: ubuntu-24.04

  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 🔐 Docker Hub login (put creds in repo Secrets)
    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    # --- Backend ---
    - name: Build image and push backend
      uses: docker/build-push-action@v6
      with:
        # relative path where the backend Dockerfile lives
        context: ./simple-api-student-main
        file: ./simple-api-student-main/Dockerfile
        # Note: tags must be lowercase
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:${{ github.sha }}
        # build on any branch; push only on main
        push: ${{ github.ref == 'refs/heads/main' }}

    # --- Database ---
    # Expect a Dockerfile at ./database/Dockerfile (e.g., FROM postgres:17-alpine)
    - name: Build image and push database
      uses: docker/build-push-action@v6
      with:
        context: ./database
        file: ./database/Dockerfile
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:${{ github.sha }}
        push: ${{ github.ref == 'refs/heads/main' }}

    # --- Httpd ---
    # Expect a Dockerfile at ./web/Dockerfile (copies index.html + httpd.conf)
    - name: Build image and push httpd
      uses: docker/build-push-action@v6
      with:
        context: ./web
        file: ./web/Dockerfile
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:${{ github.sha }}
        push: ${{ github.ref == 'refs/heads/main' }}
