name: CI devops 2025

on:
  workflow_dispatch:
  push:
    branches: ["**"]

jobs:
  ci-build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      # Test & build your Maven app (adjust path if your pom.xml is elsewhere)
      - name: Maven verify
        run: mvn -B -ntp -f simple-api-student-main/pom.xml clean verify

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api-student-main
          file: ./simple-api-student-main/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:${{ github.sha }}
          # build on any branch; push only on main or manual run
          push: ${{ github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
