name: CI devops 2025 bymaf

on:
  workflow_dispatch:               # manual trigger
  push:
    branches: ["**"]               # build on any branch
  pull_request:
    branches: ["**"]

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # Build & test if the module is in subfolder simple-api-student-main
      - name: Build and test with Maven (subfolder)
        if: ${{ hashFiles('simple-api-student-main/pom.xml') != '' }}
        run: mvn -B -ntp -f simple-api-student-main/pom.xml clean verify

      # Fallback: Build & test from repo root if no subfolder pom
      - name: Build and test with Maven (repo root)
        if: ${{ hashFiles('simple-api-student-main/pom.xml') == '' && hashFiles('pom.xml') != '' }}
        run: mvn -B -ntp clean verify

      # --- SonarCloud analysis ---
      # We only attempt Sonar if:
      #   - this is NOT a pull_request
      #   - the submodule pom exists
      #
      # We don't reference secrets.* in the if: to avoid parser drama.
      - name: SonarCloud scan
        if: ${{ hashFiles('simple-api-student-main/pom.xml') != '' && github.event_name != 'pull_request' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          echo "=== SonarCloud step starting ==="
          if [ -z "$SONAR_TOKEN" ]; then
            echo "SONAR_TOKEN is NOT set. Skipping Sonar analysis."
            exit 0
          fi

          echo "SONAR_TOKEN is present. Running mvn verify sonar:sonar ..."
          mvn -B -f simple-api-student-main/pom.xml \
            verify sonar:sonar \
            -Dsonar.projectKey="Fa-Amine_Actions" \
            -Dsonar.organization="fa-amine" \
            -Dsonar.host.url="https://sonarcloud.io" \
            -Dsonar.login="$SONAR_TOKEN" \
          || {
            echo "SonarCloud analysis failed, but continuing the pipeline (not blocking)."
            exit 0
          }

          echo "=== SonarCloud step done ==="

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Backend image ---
      - name: Build image and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api-student-main
          file: ./simple-api-student-main/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:${{ github.sha }}
          push: ${{ github.ref_name == 'master' || github.ref_name == 'main' || github.event_name == 'workflow_dispatch' }}

      # --- Database image (optional) ---
      - name: Build image and push database
        if: ${{ hashFiles('database/Dockerfile') != '' }}
        uses: docker/build-push-action@v6
        with:
          context: ./database
          file: ./database/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:${{ github.sha }}
          push: ${{ github.ref_name == 'master' || github.ref_name == 'main' || github.event_name == 'workflow_dispatch' }}

      # --- Httpd image (optional) ---
      - name: Build image and push httpd
        if: ${{ hashFiles('web/Dockerfile') != '' }}
        uses: docker/build-push-action@v6
        with:
          context: ./web
          file: ./web/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:${{ github.sha }}
          push: ${{ github.ref_name == 'master' || github.ref_name == 'main' || github.event_name == 'workflow_dispatch' }}
