name: CI devops 2025 maf

on:
  workflow_dispatch:                 # manual trigger
  push:
    branches: ["**"]                 # build on any branch
  pull_request:
    branches: ["**"]

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # --- SonarCloud (project in ./simple-api) ---
      - name: Build, test & analyze (simple-api)
        if: ${{ hashFiles('simple-api/pom.xml') != '' && github.event_name != 'pull_request' && secrets.SONAR_TOKEN != '' }}
        run: |
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=<your-project-key> \
            -Dsonar.organization=<your-organization> \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            --file ./simple-api/pom.xml

      # --- SonarCloud (project in ./simple-api-student-main) ---
      - name: Build, test & analyze (simple-api-student-main)
        if: ${{ hashFiles('simple-api-student-main/pom.xml') != '' && github.event_name != 'pull_request' && secrets.SONAR_TOKEN != '' }}
        run: |
          mvn -B verify sonar:sonar \
            -Dsonar.projectKey=<your-project-key> \
            -Dsonar.organization=<your-organization> \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            --file ./simple-api-student-main/pom.xml

      # --- Fallback: plain build on PRs or when SONAR_TOKEN is missing ---
      - name: Build & test (no Sonar)
        if: ${{ github.event_name == 'pull_request' || secrets.SONAR_TOKEN == '' }}
        shell: bash
        run: |
          if [ -f simple-api/pom.xml ]; then
            mvn -B -ntp -f simple-api/pom.xml clean verify
          elif [ -f simple-api-student-main/pom.xml ]; then
            mvn -B -ntp -f simple-api-student-main/pom.xml clean verify
          else
            mvn -B -ntp clean verify
          fi

  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # --- Backend image (simple-api-student-main) ---
      - name: Build & push backend (simple-api-student-main)
        if: ${{ hashFiles('simple-api-student-main/Dockerfile') != '' }}
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api-student-main
          file: ./simple-api-student-main/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:${{ github.sha }}
          # push on master/main or manual runs
          push: ${{ github.ref_name == 'master' || github.ref_name == 'main' || github.event_name == 'workflow_dispatch' }}

      # --- Backend image (simple-api) ---
      - name: Build & push backend (simple-api)
        if: ${{ hashFiles('simple-api/Dockerfile') != '' && hashFiles('simple-api-student-main/Dockerfile') == '' }}
        uses: docker/build-push-action@v6
        with:
          context: ./simple-api
          file: ./simple-api/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-simple-api:${{ github.sha }}
          push: ${{ github.ref_name == 'master' || github.ref_name == 'main' || github.event_name == 'workflow_dispatch' }}

      # --- Database image (optional) ---
      - name: Build & push database
        if: ${{ hashFiles('database/Dockerfile') != '' }}
        uses: docker/build-push-action@v6
        with:
          context: ./database
          file: ./database/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:${{ github.sha }}
          push: ${{ github.ref_name == 'master' || github.ref_name == 'main' || github.event_name == 'workflow_dispatch' }}

      # --- Httpd image (optional) ---
      - name: Build & push httpd
        if: ${{ hashFiles('web/Dockerfile') != '' }}
        uses: docker/build-push-action@v6
        with:
          context: ./web
          file: ./web/Dockerfile
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:${{ github.sha }}
          push: ${{ github.ref_name == 'master' || github.ref_name == 'main' || github.event_name == 'workflow_dispatch' }}
